image: golang:1.21

before_script:
  - echo "machine $CI_SERVER_HOST login gitlab-ci-token password $CI_JOB_TOKEN" >> ~/.netrc
  - export GOPRIVATE=${CI_SERVER_HOST}
  - source ~/.gvm/scripts/gvm || echo "Failed to source GVM"
  - gvm use go1.21.12 --default || echo "Failed to use GVM"
  - go version

after_script:
  - rm ~/.netrc

stages:
  - lint
  - test

lint:
  stage: lint
  image: golangci/golangci-lint:v1.52.2
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_TAG == null
      when: on_success
  script:
    - golangci-lint run -v
  before_script:
    - echo "before_script"
  after_script:
    - echo "after_script"

test:
  stage: test
  tags:
    - go
  rules:
    - if: $CI_COMMIT_TAG == null
      when: on_success
  script:
    - go test ./...