run:
  timeout: 5m
  tests: false

linters:
  disable-all: true
  enable:
    - goconst
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - unconvert
    - typecheck
    - unused
    - staticcheck
    - durationcheck
    - exportloopref
    - whitespace

linters-settings:
  gofmt:
    simplify: true
  goconst:
    min-len: 3
    min-occurrences: 6

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0